package analysis

import (
	"fmt"
	"sort"
	"strings"
)

func spl2Capabilities() CapabilityManifest {
	m := CapabilityManifest{SchemaVersion: 1, Language: "spl2", Profile: "splunkd", Version: "current", Commands: []Capability{}, Functions: []Capability{}}
	for _, entry := range spl2CommandInventory {
		limits := []string{entry.limitation}
		limits = append(limits, spl2FormLimitations(entry.name)...)
		m.Commands = append(m.Commands, Capability{Name: entry.name, SyntaxSupported: entry.syntax, SemanticSupported: entry.semantic, Limitations: limits})
	}
	for name, spec := range spl2Functions {
		limit := fmt.Sprintf("%d to %d positional arguments", spec.min, spec.max)
		if spec.max < 0 {
			limit = fmt.Sprintf("at least %d positional arguments", spec.min)
		}
		if name == "case" {
			limit += " in condition/value pairs"
		}
		if spec.aggregate {
			limit += "; aggregate context only"
		} else {
			limit += "; expression context only"
		}
		limit += "; conditional availability follows expression evidence; named arguments remain incomplete"
		m.Functions = append(m.Functions, Capability{Name: name, SyntaxSupported: true, SemanticSupported: true, Limitations: append([]string{limit}, spl2FormLimitations("function:"+name)...)})
	}
	sort.Slice(m.Commands, func(i, j int) bool { return m.Commands[i].Name < m.Commands[j].Name })
	sort.Slice(m.Functions, func(i, j int) bool { return m.Functions[i].Name < m.Functions[j].Name })
	return m
}

type spl2CapabilityEntry struct {
	name             string
	syntax, semantic bool
	limitation       string
}
type spl2CapabilityForm struct{ id, disposition, owners string }

func spl2FormLimitations(owner string) []string {
	out := []string{}
	for _, f := range spl2FormInventory {
		for _, name := range strings.Fields(f.owners) {
			if name == owner {
				out = append(out, "form "+f.id+": "+f.disposition+"; syntax obligations only; semantic support is restricted to modeled arguments and field evidence.")
			}
		}
	}
	for _, f := range spl2HeldForms {
		for _, name := range strings.Fields(f.owners) {
			if name == owner {
				out = append(out, f.id+": held; disputed syntax/effects remain incomplete and have no completed coverage credit.")
			}
		}
	}
	return out
}

// Private inventory and form dispositions transcribed from durable SPL2 provenance.
// Active denotes tested syntax obligations, including malformed witnesses; it
// is not an assertion of complete semantics for every argument or held form.
var spl2CommandInventory = []spl2CapabilityEntry{
	{"addinfo", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"append", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"appendcols", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"appendpipe", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"bin", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"branch", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"convert", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"decrypt", false, false, "Outside splunkd; located SPL_PROFILE_MISMATCH, invalid with incomplete coverage."},
	{"dedup", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"eval", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"eventstats", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"expand", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"fields", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"fieldsummary", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"fillnull", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"flatten", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"from", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"head", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"if", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"into", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"iplocation", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"join", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"loadjob", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"lookup", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"makemv", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"makeresults", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"mstats", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"mvcombine", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"mvexpand", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"nomv", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"ocsf", false, false, "Outside splunkd; located SPL_PROFILE_MISMATCH, invalid with incomplete coverage."},
	{"rename", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"replace", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"reverse", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"rex", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"route", false, false, "Outside splunkd; located SPL_PROFILE_MISMATCH, invalid with incomplete coverage."},
	{"search", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"select", true, true, "SQL phases use source, filter, group, SELECT, HAVING, order and projection; joins, hidden visibility, sibling alias collisions and unproved compound outputs remain incomplete."},
	{"sort", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"spath", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"spl1", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"stats", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"streamstats", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"table", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
	{"tags", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"thru", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"timechart", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"timewrap", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"tstats", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"typer", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"union", true, false, "Dedicated grammar; child reads are retained where owned, but command output effects remain incomplete."},
	{"untable", false, false, "Known native command; grammar and effects remain deferred and incomplete."},
	{"where", true, true, "Approved ordinary forms; unknown arguments, dynamic paths, ambiguous source identity and unproved output labels retain incomplete coverage."},
}
var spl2FormInventory = []spl2CapabilityForm{
	{"C01", "active", "search"},
	{"C02", "active", "from select"},
	{"C03", "active", "eval"},
	{"C04", "active", "where"},
	{"C05", "active", "fields"},
	{"C06", "active", "table"},
	{"C07", "active", "rename"},
	{"C08", "active", "stats"},
	{"C09", "active", "eventstats"},
	{"C10", "active", "streamstats"},
	{"C11", "active", "lookup"},
	{"C12", "active", "sort"},
	{"C13", "active", "dedup"},
	{"C14", "active", "head"},
	{"C15", "active", "reverse"},
	{"C16", "active", "join"},
	{"C17", "active", "append"},
	{"C18", "active", "appendpipe"},
	{"C19", "active", "appendcols"},
	{"C20", "active", "union"},
	{"C21", "active", "if"},
	{"C22", "active", "spl1"},
	{"C23", "active", "bin"},
	{"C24", "active", "rex"},
	{"C25", "active", "spath"},
	{"C26", "active", "makeresults"},
	{"C27", "active", "loadjob"},
	{"C28", "active", "tstats"},
	{"C29", "active", "mstats"},
	{"C30", "active", "timechart"},
	{"C31", "active", "timewrap"},
	{"C32", "active", "makemv"},
	{"C33", "active", "mvexpand"},
	{"C34", "active", "mvcombine"},
	{"C35", "active", "fillnull"},
	{"L01", "active", "eval"},
	{"L02", "active", "eval"},
	{"L03", "active", "eval"},
	{"L04", "active", "eval"},
	{"L05", "active", "eval"},
	{"L06", "active", "eval"},
	{"L07", "active", "eval"},
	{"L08", "active", "eval"},
	{"L09", "active", "eval"},
	{"L10", "active", "eval"},
	{"L11", "active", "eval"},
	{"L12", "active", "eval"},
	{"L13", "active", "eval"},
	{"L14", "active", "eval"},
	{"L15", "active", "from select"},
	{"L16", "active", "from select"},
	{"L17", "active", "from select"},
	{"L18", "active", "eval"},
	{"L19", "active", "from select"},
	{"L20", "active", "eval"},
	{"L21", "active", "eval"},
	{"L22", "active", "eval"},
	{"L23", "active", "eval"},
	{"L24", "active", "eval"},
	{"L25", "active", "eval"},
	{"Q01", "active", "from select"},
	{"Q02", "active", "from select"},
	{"Q03", "active", "from select"},
	{"Q04", "active", "from select"},
	{"Q05", "active", "from select"},
	{"Q06", "active", "from select"},
	{"Q07", "active", "from select"},
	{"Q08", "active", "from select"},
	{"E.C01.literal", "active", "search"},
	{"E.C01.comparison", "active", "search"},
	{"E.C01.in", "active", "search"},
	{"E.C01.term", "active", "search"},
	{"E.C01.case", "active", "search"},
	{"E.C01.boolean", "active", "search"},
	{"E.C01.selector", "active", "search"},
	{"E.C01.relative_time", "active", "search"},
	{"E.C01.absolute_time", "active", "search"},
	{"E.C01.index_time", "active", "search"},
	{"E.C03.assign", "active", "eval"},
	{"E.C04.predicate", "active", "where"},
	{"E.C05.include", "active", "fields"},
	{"E.C05.exclude", "active", "fields"},
	{"E.C06.exact", "active", "table"},
	{"E.C07.exact", "active", "rename"},
	{"E.C07.wildcard", "active", "rename"},
	{"E.C08.calls", "active", "stats"},
	{"E.C08.by_span", "active", "stats"},
	{"E.C09.calls", "active", "eventstats"},
	{"E.C09.by_span", "active", "eventstats"},
	{"E.C10.calls", "active", "streamstats"},
	{"E.C10.reset_before", "active", "streamstats"},
	{"E.C10.reset_after", "active", "streamstats"},
	{"E.C10.reset_onchange", "active", "streamstats"},
	{"E.C11.matches", "active", "lookup"},
	{"E.C11.output", "active", "lookup"},
	{"E.C11.outputnew", "active", "lookup"},
	{"E.C12.order_terms", "active", "sort"},
	{"E.C12.count", "active", "sort"},
	{"E.C13.count", "active", "dedup"},
	{"E.C14.while", "active", "head"},
	{"E.C14.count", "active", "head"},
	{"E.C08.allnum", "active", "stats"},
	{"E.C09.allnum", "active", "eventstats"},
	{"E.C10.current", "active", "streamstats"},
	{"E.C13.keepempty", "active", "dedup"},
	{"E.C13.consecutive", "active", "dedup"},
	{"E.C14.keeplast", "active", "head"},
	{"E.C18.run_in_preview", "active", "appendpipe"},
	{"E.C30.partial", "active", "timechart"},
	{"E.C30.cont", "active", "timechart"},
	{"E.C30.fixedrange", "active", "timechart"},
	{"E.C30.usenull", "active", "timechart"},
	{"E.C30.useother", "active", "timechart"},
	{"E.C08.delim", "active", "stats"},
	{"E.C30.sep", "active", "timechart"},
	{"E.C30.format", "active", "timechart"},
	{"E.C30.nullstr", "active", "timechart"},
	{"E.C30.otherstr", "active", "timechart"},
	{"E.C08.partitions", "active", "stats"},
	{"E.C10.window", "active", "streamstats"},
	{"E.C16.type", "active", "join"},
	{"E.C16.max", "active", "join"},
	{"E.C16.alias_predicate", "active", "join"},
	{"E.C17.subsearch", "active", "append"},
	{"E.C18.subpipe", "active", "appendpipe"},
	{"E.C19.subsearch", "active", "appendcols"},
	{"E.C20.dataset_types", "active", "union"},
	{"E.C21.paths", "active", "if"},
	{"E.C22.explicit", "active", "spl1"},
	{"E.C22.backtick", "active", "spl1"},
	{"E.C23.bins", "active", "bin"},
	{"E.C23.minspan", "active", "bin"},
	{"E.C23.span_length", "active", "bin"},
	{"E.C23.span_log", "active", "bin"},
	{"E.C23.start", "active", "bin"},
	{"E.C23.end", "active", "bin"},
	{"E.C23.aligntime", "active", "bin"},
	{"E.C23.alias", "active", "bin"},
	{"E.C24.field", "active", "rex"},
	{"E.C24.max_match", "active", "rex"},
	{"E.C24.offset_field", "active", "rex"},
	{"E.C24.quoted_regex", "active", "rex"},
	{"E.C24.raw_regex", "active", "rex"},
	{"E.C24.slash_regex", "active", "rex"},
	{"E.C24.sed", "active", "rex"},
	{"E.C25.input", "active", "spath"},
	{"E.C25.path", "active", "spath"},
	{"E.C25.output", "active", "spath"},
	{"E.C26.count", "active", "makeresults"},
	{"E.C27.sid", "active", "loadjob"},
	{"E.C28.aggregates", "active", "tstats"},
	{"E.C28.predicate", "active", "tstats"},
	{"E.C28.byfields", "active", "tstats"},
	{"E.C29.aggregates", "active", "mstats"},
	{"E.C29.predicate", "active", "mstats"},
	{"E.C29.byfields", "active", "mstats"},
	{"E.C28.datamodel_name", "active", "tstats"},
	{"E.C30.limit", "active", "timechart"},
	{"E.C30.agg", "active", "timechart"},
	{"E.C30.eval_expression", "active", "timechart"},
	{"E.C30.single_aggregate", "active", "timechart"},
	{"E.C30.bins", "active", "timechart"},
	{"E.C30.minspan", "active", "timechart"},
	{"E.C30.span", "active", "timechart"},
	{"E.C30.start", "active", "timechart"},
	{"E.C30.end", "active", "timechart"},
	{"E.C30.aligntime", "active", "timechart"},
	{"E.C30.weekly_snap", "active", "timechart"},
	{"E.C31.span", "active", "timewrap"},
	{"E.C31.align", "active", "timewrap"},
	{"E.C32.delim", "active", "makemv"},
	{"E.C32.tokenizer", "active", "makemv"},
	{"E.C33.limit", "active", "mvexpand"},
	{"E.C34.delim", "active", "mvcombine"},
	{"E.C35.value", "active", "fillnull"},
	{"E.C35.fields", "active", "fillnull"},
	{"E.L01.start", "active", "eval"},
	{"E.L02.identifier", "active", "eval"},
	{"E.L03.number", "active", "eval"},
	{"E.L03.raw", "active", "eval"},
	{"E.L03.null_boolean", "active", "eval"},
	{"E.L04.comments", "active", "eval"},
	{"E.L06.precedence", "active", "eval"},
	{"E.L07.between", "active", "eval"},
	{"E.L07.in", "active", "eval"},
	{"E.L07.like", "active", "eval"},
	{"E.L07.is_null", "active", "eval"},
	{"E.L07.is_type", "active", "eval"},
	{"E.L08.array", "active", "eval"},
	{"E.L08.object_keys", "active", "eval"},
	{"E.L08.duplicate_keys", "active", "eval"},
	{"E.L09.dot", "active", "eval"},
	{"E.L09.bracket", "active", "eval"},
	{"E.L10.string_template", "active", "eval"},
	{"E.L10.field_template", "active", "eval"},
	{"E.L11.one_param", "active", "eval"},
	{"E.L11.zero_multi", "active", "eval"},
	{"E.L11.typed_default", "active", "eval"},
	{"E.L11.block", "active", "eval"},
	{"E.L11.shortcut", "active", "eval"},
	{"E.L15.from_clauses", "active", "from select"},
	{"E.L16.select_clauses", "active", "from select"},
	{"E.L16.distinct", "active", "from select"},
	{"E.L16.alias", "active", "from select"},
	{"E.L16.group_keys", "active", "from select"},
	{"E.L16.group_span", "active", "from select"},
	{"E.L16.having", "active", "from select"},
	{"E.L16.order", "active", "from select"},
	{"E.L16.limit_offset", "active", "from select"},
	{"E.L17.pipe", "active", "from select"},
	{"E.L18.rows", "active", "eval"},
	{"E.L19.inner", "active", "from select"},
	{"E.L19.left", "active", "from select"},
	{"E.L19.multiple_join", "active", "from select"},
	{"E.L07.exists", "active", "eval"},
	{"E.L24.search_literal", "active", "eval"},
	{"E.L06.named_arguments", "active", "eval"},
	{"F.abs", "active", "function:abs"},
	{"F.ceil", "active", "function:ceil"},
	{"F.ceiling", "active", "function:ceiling"},
	{"F.floor", "active", "function:floor"},
	{"F.round", "active", "function:round"},
	{"F.len", "active", "function:len"},
	{"F.lower", "active", "function:lower"},
	{"F.upper", "active", "function:upper"},
	{"F.trim", "active", "function:trim"},
	{"F.ltrim", "active", "function:ltrim"},
	{"F.rtrim", "active", "function:rtrim"},
	{"F.substr", "active", "function:substr"},
	{"F.replace", "active", "function:replace"},
	{"F.coalesce", "active", "function:coalesce"},
	{"F.if", "active", "function:if"},
	{"F.case", "active", "function:case"},
	{"F.match", "active", "function:match"},
	{"F.isnull", "active", "function:isnull"},
	{"F.isnotnull", "active", "function:isnotnull"},
	{"F.tonumber", "active", "function:tonumber"},
	{"F.tostring", "active", "function:tostring"},
	{"F.mvcount", "active", "function:mvcount"},
	{"F.split", "active", "function:split"},
	{"F.count", "active", "function:count"},
	{"F.sum", "active", "function:sum"},
	{"F.avg", "active", "function:avg"},
	{"F.min", "active", "function:min"},
	{"F.max", "active", "function:max"},
	{"F.dc", "active", "function:dc"},
	{"F.distinct_count", "active", "function:distinct_count"},
	{"F.values", "active", "function:values"},
	{"F.list", "active", "function:list"},
	{"F.first", "active", "function:first"},
	{"F.last", "active", "function:last"},
	{"exclusions", "active", "eval"},
	{"I.assign", "active", "eval"},
	{"I.bin", "active", "bin"},
	{"I.timechart", "active", "timechart"},
	{"I.named", "active", "eval"},
	{"I.object", "active", "eval"},
	{"I.literal", "active", "eval"},
	{"T6.canonical", "active", "eval"},
	{"T8.canonical", "active", "eval"},
}
var spl2HeldForms = []spl2CapabilityForm{
	{"H01", "held", "table"},
	{"H02", "held", "streamstats"},
	{"H03", "held", "head"},
	{"H04", "held", "timechart"},
	{"H05", "held", "eval from select"},
	{"H06", "held", "from select"},
	{"H07", "held", "from select"},
	{"H08", "held", "from select"},
	{"H09", "held", "from select"},
	{"H10", "held", "spl1 eval from select"},
	{"H11", "held", "eval where search join from select"},
	{"H12", "held", "rex"},
	{"EH01", "held", "bin"},
	{"EH02", "held", "timechart"},
	{"EH03", "held", "search"},
	{"EH04", "held", "eval where"},
	{"EH05", "held", "from select"},
}
