parser grammar SPL2Parser;
options { tokenVocab=SPL2Lexer; }

query: NL* (pipeline moduleSuffix? | moduleDeclaration) NL* EOF;
pipeline: start (NL* PIPE NL* command)*;
start: fromCommand | selectCommand | searchCommand | implicitSearch | generator | embeddedCommand;
command: evalCommand | whereCommand | fieldsCommand | fromCommand | selectCommand | searchCommand | rexCommand | embeddedCommand;
fromCommand: FROM dataset;
selectCommand: SELECT projection (COMMA projection)* FROM dataset;
projection: expression (AS identifier)?;
dataset: identifier | array;
generator: MAKERESULTS NUMBER?;
evalCommand: EVAL assignment (COMMA assignment)*;
assignment: fieldName ASSIGN expression;
whereCommand: WHERE expression;
fieldsCommand: (FIELDS | TABLE) (PLUS | MINUS)? identifier (COMMA identifier)*;
rexCommand: REX rexOption* (REGEX | stringLiteral | RAW_STRING);
rexOption: IDENTIFIER ASSIGN (identifier | NUMBER);
embeddedCommand: SPL1? embeddedText;
embeddedText: BACKTICK EMBEDDED_TEXT? EMBEDDED_END;
moduleSuffix: SEMI .*?;
moduleDeclaration: (IMPORT | EXPORT | FUNCTION | LOCAL ASSIGN) .*?;

searchCommand: SEARCH searchExpression;
implicitSearch: INDEX ASSIGN searchValue searchExpression?;
searchExpression: searchXor;
searchXor: searchAnd (XOR searchAnd)*;
searchAnd: searchOr (AND? searchOr)*;
searchOr: searchNot (OR searchNot)*;
searchNot: NOT searchNot | searchAtom;
searchAtom: LPAREN searchExpression RPAREN | identifier comparison searchValue | identifier IN LPAREN searchValue (COMMA searchValue)+ RPAREN | searchValue;
searchValue: identifier | NUMBER | stringLiteral | RAW_STRING | STAR;

expression: lambdaExpression | xorExpression;
xorExpression: orExpression (XOR orExpression)*;
orExpression: andExpression (OR andExpression)*;
andExpression: notExpression (AND notExpression)*;
notExpression: NOT notExpression | predicate;
predicate: additive (comparison additive | NOT? BETWEEN additive AND additive | NOT? IN LPAREN expression (COMMA expression)* RPAREN | NOT? LIKE additive | IS (NOT? (NULL | NULL_TEST) | NOT? TYPE))?;
comparison: ASSIGN | EQ | NE | LT | LE | GT | GE;
additive: multiplicative ((PLUS | MINUS) multiplicative)*;
multiplicative: unary ((STAR | SLASH | MOD) unary)*;
unary: (PLUS | MINUS) unary | access;
access: primary accessPart*;
accessPart: DOT identifier | LBRACKET expression RBRACKET;
primary: call | fieldName | LOCAL | literal | array | object | LPAREN expression RPAREN | searchLiteral;
call: identifier LPAREN arguments? RPAREN;
arguments: namedArgument (COMMA namedArgument)* | expression (COMMA expression)* (COMMA namedArgument)*;
namedArgument: identifier COLON expression;
literal: NUMBER | BOOLEAN | NULL | RAW_STRING | stringLiteral;
stringLiteral: DQUOTE (STRING_TEXT | STRING_DOLLAR | STRING_INTERPOLATION expression RBRACE)* STRING_END;
quotedName: SQUOTE (NAME_TEXT | NAME_DOLLAR)+ NAME_END;
fieldTemplate: SQUOTE (NAME_TEXT | NAME_DOLLAR)* NAME_INTERPOLATION expression RBRACE (NAME_TEXT | NAME_DOLLAR | NAME_INTERPOLATION expression RBRACE)* NAME_END;
fieldName: identifier | fieldTemplate;
identifier: IDENTIFIER | INDEX | quotedName;
array: LBRACKET (expression (COMMA expression)* COMMA?)? RBRACKET;
object: LBRACE (objectEntry (COMMA objectEntry)* COMMA?)? RBRACE;
objectEntry: objectKey COLON expression;
objectKey: identifier | stringLiteral;
searchLiteral: embeddedText;
lambdaExpression: (lambdaParameter | LPAREN (lambdaParameter (COMMA lambdaParameter)*)? RPAREN) ARROW (expression | lambdaBlock);
lambdaParameter: LOCAL (COLON TYPE)? (ASSIGN ((PLUS | MINUS)? NUMBER | stringLiteral))?;
lambdaBlock: LBRACE NL* (LOCAL ASSIGN expression (SEMI NL* | NL+))* RETURN expression SEMI? NL* RBRACE;
